### ISSUE TITLE
Error while trying to run backup

### ISSUE THREAD

**Issue by M-M-M-M** [mrichtarsky/glacier_deep_archive_backup#4]
Under Rocky Linux release 8.6 (Green Obsidian)
Python 3.6.8

```
./backup_scratch config/backup.sh
Scratch backup, timestamp: 2022-09-23-090008 (needed if resume is necessary)
  File "<fstring>", line 1
    (path=)
         ^
SyntaxError: invalid syntax
```

**Comment by mrichtarsky** [comment]
I guess the output above is incorrect, it should be `{path=}` in `create_sets.py:38`:

`print(f"Set: {path=}, {len(items)} item(s), {size_to_string(size)}")`

Unfortunately the nice `{path=}` f-string syntax was added after python3.6. I will just change it to work in 3.6 also.

**Comment by M-M-M-M** [comment]
I have now other errors:

```
./backup_scratch config/backup.sh
Scratch backup, timestamp: 2022-09-23-112122 (needed if resume is necessary)
Crawling /snapshot_aws_backup/mailserver-220724-061501.tar.gz
find: Arguments to -type should contain only one letter
Traceback (most recent call last):
  File "impl/create_sets.py", line 234, in <module>
    crawl_and_write(snapshot_path, backup_paths, upload_limit, state_file)
  File "impl/create_sets.py", line 214, in crawl_and_write
    root_node = crawl(snapshot_path, backup_paths, upload_limit)
  File "impl/create_sets.py", line 203, in crawl
    update_find_counters(path, sub_num_files, sub_size_files)
  File "impl/create_sets.py", line 151, in update_find_counters
    sub_num_files.verify()
  File "impl/create_sets.py", line 139, in verify
    raise Exception(msg)
Exception: Mismatch: subfiles: walk=1, find=0, diff: 1

```

**Comment by mrichtarsky** [comment]
Your system does not support GNU extensions. I've changed the `find` calls to POSIX.

**Comment by M-M-M-M** [comment]
I have now:
```

./backup_scratch config/backup.sh
Scratch backup, timestamp: 2022-09-24-134827 (needed if resume is necessary)
Crawling /snapshot_aws_backup/mailserver-220724-061501.tar.gz
Traceback (most recent call last):
  File "impl/create_sets.py", line 234, in <module>
    crawl_and_write(snapshot_path, backup_paths, upload_limit, state_file)
  File "impl/create_sets.py", line 214, in crawl_and_write
    root_node = crawl(snapshot_path, backup_paths, upload_limit)
  File "impl/create_sets.py", line 192, in crawl
    process_file(path)
  File "impl/create_sets.py", line 177, in process_file
    info = os.lstat(file_path) # Do not follow symlinks
FileNotFoundError: [Errno 2] No such file or directory: '/snapshot_aws_backup/mailserver-220724-061501.tar.gz'
```

On RockyLinux (Centos/RedHat) it is a Gnu find:
```

find --version
find (GNU findutils) 4.6.0
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION SELINUX FTS(FTS_CWDFD) CBO(level=2)
```

**Comment by mrichtarsky** [comment]
What does `ls -al /snapshot_aws_backup/mailserver-220724-061501.tar.gz` show?

**Comment by M-M-M-M** [comment]
```
#ls -al /snapshot_aws_backup/mailserver-220724-061501.tar.gz
ls: cannot access '/snapshot_aws_backup/mailserver-220724-061501.tar.gz': No such file or directory
```

but I have run the command many times.
There are a lot of other files:
```
#ls /snapshot_aws_backup
mailserver-220725-061501.tar.gz  mailserver-220803-061501.tar.gz  mailserver-220812-061501.tar.gz  mailserver-220821-061501.tar.gz  mailserver-220830-061501.tar.gz  mailserver-220908-061501.tar.gz  mailserver-220917-061501.tar.gz
mailserver-220725-154801.tar.gz  mailserver-220803-154801.tar.gz  mailserver-220812-154801.tar.gz  mailserver-220821-154801.tar.gz  mailserver-220830-154801.tar.gz  mailserver-220908-154801.tar.gz  mailserver-220917-154801.tar.gz
mailserver-220726-061501.tar.gz  mailserver-220804-061501.tar.gz  mailserver-220813-061501.tar.gz  mailserver-220822-061501.tar.gz  mailserver-220831-061501.tar.gz  mailserver-220909-061501.tar.gz  mailserver-220918-061501.tar.gz
mailserver-220726-154802.tar.gz  mailserver-220804-154801.tar.gz  mailserver-220813-154801.tar.gz  mailserver-220822-154801.tar.gz  mailserver-220831-154801.tar.gz  mailserver-220909-154801.tar.gz  mailserver-220918-154801.tar.gz
mailserver-220727-061501.tar.gz  mailserver-220805-061501.tar.gz  mailserver-220814-061501.tar.gz  mailserver-220823-061501.tar.gz  mailserver-220901-061501.tar.gz  mailserver-220910-061501.tar.gz  mailserver-220919-154801.tar.gz
mailserver-220727-154801.tar.gz  mailserver-220805-154802.tar.gz  mailserver-220814-154801.tar.gz  mailserver-220823-154801.tar.gz  mailserver-220901-154801.tar.gz  mailserver-220910-154801.tar.gz  mailserver-220920-061502.tar.gz
mailserver-220728-061502.tar.gz  mailserver-220806-061501.tar.gz  mailserver-220815-061501.tar.gz  mailserver-220824-061501.tar.gz  mailserver-220902-061501.tar.gz  mailserver-220911-061501.tar.gz  mailserver-220920-154801.tar.gz
mailserver-220728-154801.tar.gz  mailserver-220806-154801.tar.gz  mailserver-220815-154801.tar.gz  mailserver-220824-154801.tar.gz  mailserver-220902-154801.tar.gz  mailserver-220911-154801.tar.gz  mailserver-220921-061502.tar.gz
mailserver-220729-061502.tar.gz  mailserver-220807-061501.tar.gz  mailserver-220816-061501.tar.gz  mailserver-220825-061501.tar.gz  mailserver-220903-061501.tar.gz  mailserver-220912-061501.tar.gz  mailserver-220921-154801.tar.gz
mailserver-220729-154801.tar.gz  mailserver-220807-154801.tar.gz  mailserver-220816-154801.tar.gz  mailserver-220825-154801.tar.gz  mailserver-220903-154801.tar.gz  mailserver-220912-154801.tar.gz  mailserver-220922-061501.tar.gz
mailserver-220730-061501.tar.gz  mailserver-220808-061501.tar.gz  mailserver-220817-061501.tar.gz  mailserver-220826-061501.tar.gz  mailserver-220904-061501.tar.gz  mailserver-220913-061501.tar.gz  mailserver-220922-154801.tar.gz
mailserver-220730-154801.tar.gz  mailserver-220808-154801.tar.gz  mailserver-220817-154801.tar.gz  mailserver-220826-154801.tar.gz  mailserver-220904-154801.tar.gz  mailserver-220913-154801.tar.gz  mailserver-220923-061501.tar.gz
mailserver-220731-061501.tar.gz  mailserver-220809-061501.tar.gz  mailserver-220818-061501.tar.gz  mailserver-220827-061501.tar.gz  mailserver-220905-061501.tar.gz  mailserver-220914-061501.tar.gz  mailserver-220923-154801.tar.gz
mailserver-220731-154801.tar.gz  mailserver-220809-154801.tar.gz  mailserver-220818-154801.tar.gz  mailserver-220827-154801.tar.gz  mailserver-220905-154801.tar.gz  mailserver-220914-154801.tar.gz  mailserver-220924-061501.tar.gz
mailserver-220801-061501.tar.gz  mailserver-220810-061501.tar.gz  mailserver-220819-061501.tar.gz  mailserver-220828-061501.tar.gz  mailserver-220906-061501.tar.gz  mailserver-220915-061501.tar.gz
mailserver-220801-154801.tar.gz  mailserver-220810-154801.tar.gz  mailserver-220819-154801.tar.gz  mailserver-220828-154801.tar.gz  mailserver-220906-154801.tar.gz  mailserver-220915-154801.tar.gz
mailserver-220802-061501.tar.gz  mailserver-220811-061501.tar.gz  mailserver-220820-061502.tar.gz  mailserver-220829-061501.tar.gz  mailserver-220907-061501.tar.gz  mailserver-220916-061501.tar.gz
mailserver-220802-154801.tar.gz  mailserver-220811-154801.tar.gz  mailserver-220820-154801.tar.gz  mailserver-220829-154801.tar.gz  mailserver-220907-154801.tar.gz  mailserver-220916-154801.tar.gz
```

There are several ZFS snapshots:
```
#zfs list -t snapshot
NAME                                                       USED  AVAIL     REFER  MOUNTPOINT
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-084317     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-084829     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-085009     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-085021     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-085226     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-085245     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-085309     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-090008     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-23-112122     0B      -      103M  -
myzpool/BACKUP/mailserver@snapshot-aws-2022-09-24-134827    64K      -      103M  -
```

**Comment by mrichtarsky** [comment]
Looking at the output I think you specified `mailserver-220724-061501.tar.gz` explicitly in your config file (due to lack of wildcards) but that file is now gone in your pool (automatic purging of old backups?).

**Comment by M-M-M-M** [comment]
You are right, the file was not present anymore due to some purging. 
Might be better to add a warning rather than an error: 
`Warning: the file <filename> was not found!`

**Comment by mrichtarsky** [comment]
> You are right, the file was not present anymore due to some purging. Might be better to add a warning rather than an error: `Warning: the file <filename> was not found!`

I'd rather keep the error, since the error hints at something broken in the config, and a warning might go unnoticed.

Normally you would have used a wildcard, and it would not have been an issue then.

I will make the script more robust so that snapshots are destroyed in case a backup hasn't reached resumable state,

**Comment by M-M-M-M** [comment]
okay. 

It might be good not to display the traceback or only with a --verbose option, so the output might be more readable and parsable to find the error.

**Comment by mrichtarsky** [comment]
Hmm, I would prefer to keep the traceback as is. The relevant message is at the end and easy to spot, and the traceback provides helpful context where the problem occurred.

**Comment by M-M-M-M** [comment]
Traceback is more for developers than for end-users. 
Useful for debugging to one with development knowledge in Python but useless and confusing for others that would miss the real error message after dozen of traceback lines. 
Whose the request for --verbose or --debug flag to handle that without stopping the feature for developers or for assisting in debug.

**Comment by mrichtarsky** [comment]
> > You are right, the file was not present anymore due to some purging. Might be better to add a warning rather than an error: `Warning: the file <filename> was not found!`
> 
> I'd rather keep the error, since the error hints at something broken in the config, and a warning might go unnoticed.

I have now changed it so that a warning is displayed, and when there have been any warnings, a prompt asks whether to continue. The prompt can be disabled by `IGNORE_WARNINGS=1`.

> I will make the script more robust so that snapshots are destroyed in case a backup hasn't reached resumable state,

This has been added in the meantime.

> Traceback is more for developers than for end-users. Useful for debugging to one with development knowledge in Python but useless and confusing for others that would miss the real error message after dozen of traceback lines. Whose the request for --verbose or --debug flag to handle that without stopping the feature for developers or for assisting in debug.

This has been addressed by the warning change as mentioned above.
